"""Generate data/updated_exports/data_dictionary.csv"""
import os
import pandas as pd

rows = []

def add(dataset, col, meaning, dtype, allowed, training, dashboard):
    rows.append({
        "column_name": col,
        "dataset": dataset,
        "meaning": meaning,
        "data_type": dtype,
        "allowed_values": allowed,
        "synthetic_demo": True,
        "used_in_training": training,
        "used_in_dashboard": dashboard,
    })

DS = "clean_data (patient flow, training)"
add(DS, "datetime", "Timestamp of the hourly record", "string", "ISO datetime", True, False)
add(DS, "patients", "Total patients present in hospital at this hour (primary target)", "int", "42-232", True, True)
add(DS, "day_of_week", "Integer day (0=Monday 6=Sunday)", "int", "0-6", True, False)
add(DS, "day_of_week_name", "Name of day", "string", "Monday-Sunday", True, False)
add(DS, "month", "Calendar month", "int", "1-12", True, False)
add(DS, "is_weekend", "1 if Saturday or Sunday", "int", "0 or 1", True, True)
add(DS, "holiday", "1 if hospital calendar event or public holiday", "int", "0 or 1", True, True)
add(DS, "holiday_name", "Name of holiday or event", "string", "free text or blank", True, False)
add(DS, "weather", "Weather severity code", "int", "1-3", True, True)
add(DS, "weather_type", "Weather label", "string", "Normal/Cold-Flu Season/Extreme Heat", True, False)
add(DS, "weather_severity", "Weather severity (duplicates weather column)", "int", "1-3", True, False)
add(DS, "hospital capacity", "Maximum licensed beds at this hour", "int", "218-295", True, True)
add(DS, "is_capped", "1 if patients equal capacity", "int", "0 or 1", True, False)
add(DS, "is_emergency", "1 if mass casualty or emergency event active", "int", "0 or 1", True, True)
add(DS, "emergency_spike", "Additional patients from emergency event", "int", ">=0", True, True)
add(DS, "is_outbreak", "1 if disease outbreak active", "int", "0 or 1", True, True)
add(DS, "outbreak_intensity", "Severity of outbreak (0=none 3=severe)", "int", "0-3", True, True)
add(DS, "is_staff_shortage", "1 if staff shortage in effect", "int", "0 or 1", True, True)
add(DS, "staff_shortage_impact", "Patients affected by staff shortage", "int", ">=0", True, False)
add(DS, "scenario_primary", "Human-readable scenario label", "string", "free text", True, False)
add(DS, "scenario_code", "Integer code for scenario type", "int", "0-9", True, False)
add(DS, "y_patients_t_plus_1", "Supervised label: patients 1 hour ahead", "int", "42-232", True, False)
add(DS, "y_patients_t_plus_24", "Supervised label: patients 24 hours ahead", "int", "42-232", True, False)
add(DS, "hour", "Hour of day", "int", "0-23", True, True)
add(DS, "season", "Season label", "string", "Winter/Spring/Summer/Autumn", True, True)
add(DS, "week_of_year", "ISO week number", "int", "1-52", True, False)
add(DS, "shift_period", "Shift name for this hour", "string", "Morning/Evening/Night", True, True)
add(DS, "is_holiday", "1 if holiday (alias of holiday column)", "int", "0 or 1", True, False)
add(DS, "is_holiday_or_event", "1 if holiday or special event", "int", "0 or 1", True, False)
add(DS, "event_flag", "1 if any event is active", "int", "0 or 1", True, False)
add(DS, "arrivals", "New patient arrivals this hour", "int", ">=0", True, True)
add(DS, "admissions", "Admissions from arrivals", "int", ">=0", True, False)
add(DS, "discharges", "Patients discharged this hour", "int", ">=0", True, True)
add(DS, "transfers", "Transfers between departments", "int", ">=0", True, False)
add(DS, "emergency_arrivals", "Emergency arrivals subset", "int", ">=0", True, True)
add(DS, "elective_arrivals", "Elective/planned arrivals subset", "int", ">=0", True, False)
add(DS, "waiting_patients", "Patients waiting for a bed", "int", ">=0", True, True)
add(DS, "avg_wait_time_minutes", "Average wait time in minutes", "int", ">=0", True, True)
add(DS, "occupancy_rate", "Fraction of beds occupied", "float", "0.0-1.0", True, True)
add(DS, "bed_occupancy", "Alias of occupancy_rate", "float", "0.0-1.0", True, False)
add(DS, "occupied_beds", "Count of beds in use", "int", ">=0", True, True)
add(DS, "available_beds", "Count of free beds", "int", ">=0", True, True)
add(DS, "available_doctors", "Doctors on duty this hour", "int", ">=0", True, True)
add(DS, "available_nurses", "Nurses on duty this hour", "int", ">=0", True, True)
add(DS, "staff_on_duty", "Total staff on duty", "int", ">=0", True, False)
add(DS, "doctor_shortage", "Doctors below required ratio (0 = fully staffed)", "int", ">=0", True, True)
add(DS, "nurse_shortage", "Nurses below required ratio (0 = fully staffed)", "int", ">=0", True, True)
add(DS, "bed_shortage", "Beds below required count (0 = no shortage)", "int", ">=0", True, True)
add(DS, "appointments_count", "Scheduled appointments this hour", "int", ">=0", True, False)
add(DS, "or_bookings_count", "OR bookings this hour", "int", ">=0", True, False)
add(DS, "delayed_discharge_count", "Discharges delayed this hour", "int", ">=0", True, False)
add(DS, "department_pressure_score", "Composite pressure index 0-100", "float", "0.0-100.0", True, True)
add(DS, "er_pressure_score", "ER-specific pressure index 0-100", "float", "0.0-100.0", True, True)
add(DS, "doctors_available", "Alias of available_doctors", "int", ">=0", True, False)
add(DS, "nurses_available", "Alias of available_nurses", "int", ">=0", True, False)
add(DS, "lag_1", "Patients 1 hour ago (lag feature)", "int", "42-232", True, False)
add(DS, "lag_24", "Patients 24 hours ago (lag feature)", "int", "42-232", True, False)
add(DS, "roll_mean_3", "3-hour rolling mean of patients", "float", ">=0", True, False)
add(DS, "roll_mean_6", "6-hour rolling mean of patients", "float", ">=0", True, False)
add(DS, "roll_mean_24", "24-hour rolling mean of patients", "float", ">=0", True, False)
add(DS, "predicted_patients_next_hour", "LSTM predicted value at generation time", "int", "42-232", True, False)

DS = "staff_master_data"
add(DS, "staff_id", "Unique staff identifier (STF-XXXX format)", "string", "STF-0001 to STF-0148", False, True)
add(DS, "staff_name", "Full display name", "string", "free text", False, True)
add(DS, "role", "Clinical role", "string", "doctor/nurse", False, True)
add(DS, "department", "Primary assigned department", "string", "ER/ICU/General Ward/Surgery/Radiology", False, True)
add(DS, "specialty", "Medical specialty", "string", "free text", False, True)
add(DS, "qualification_level", "Highest qualification", "string", "MD/PhD/BSN/RN/MSN", False, False)
add(DS, "years_experience", "Years in clinical practice", "int", "1-30", False, False)
add(DS, "overtime_hours", "Overtime hours this period", "int", "0-20", False, False)
add(DS, "available_for_shift", "Whether available for next shift", "string", "Yes/No", False, True)
add(DS, "max_hours_per_week", "Maximum weekly hours allowed", "int", "40/48/56", False, False)
add(DS, "notes", "Free-text operational notes", "string", "free text", False, False)

DS = "staff_schedule"
add(DS, "staff_id", "FK to staff_master staff_id (STF-XXXX)", "string", "STF-0001 to STF-0148", False, True)
add(DS, "staff_name", "Display name", "string", "free text", False, True)
add(DS, "staff_username", "Login username (lowercase stf-XXXX or named)", "string", "lowercase stf-XXXX", False, True)
add(DS, "role", "Clinical role", "string", "doctor/nurse", False, True)
add(DS, "department", "Assigned department for this shift", "string", "ER/ICU/General Ward/Surgery/Radiology", False, True)
add(DS, "shift_date", "Date of shift (YYYY-MM-DD)", "string", "ISO date", False, True)
add(DS, "shift_type", "Shift period name", "string", "Morning/Evening/Night/Emergency Backup", False, True)
add(DS, "shift_start_time", "Shift start time (HH:MM)", "string", "07:00/15:00/23:00", False, True)
add(DS, "shift_end_time", "Shift end time (HH:MM)", "string", "15:00/23:00/07:00", False, True)
add(DS, "status", "Shift assignment status", "string", "Assigned/Pending/Cancelled", False, True)
add(DS, "notes", "Free-text notes", "string", "free text", False, False)

DS = "shifts (DB seed source)"
add(DS, "staff_username", "Login username - must match users.csv/DB (lowercase stf-XXXX)", "string", "lowercase stf-XXXX", False, True)
add(DS, "name", "Display name", "string", "free text", False, True)
add(DS, "role", "Clinical role", "string", "doctor/nurse", False, True)
add(DS, "department", "Assigned department", "string", "ER/ICU/General Ward/Surgery/Radiology", False, True)
add(DS, "shift_date", "Date of shift (YYYY-MM-DD)", "string", "ISO date", False, True)
add(DS, "shift_type", "Shift period", "string", "Morning/Evening/Night/Emergency Backup", False, True)
add(DS, "shift_start_time", "Start time HH:MM", "string", "07:00/15:00/23:00", False, True)
add(DS, "shift_end_time", "End time HH:MM", "string", "15:00/23:00/07:00", False, True)
add(DS, "status", "Shift status", "string", "Assigned/Pending/Cancelled", False, True)
add(DS, "notes", "Free-text notes", "string", "Synthetic demo schedule", False, False)

DS = "appointments"
add(DS, "appointment_id", "Unique appointment identifier", "string", "APT-XXXX", False, True)
add(DS, "department", "Clinic department", "string", "ER/ICU/General Ward/Surgery/Radiology", False, True)
add(DS, "doctor", "Attending doctor name", "string", "free text", False, True)
add(DS, "date", "Appointment date (YYYY-MM-DD)", "string", "ISO date", False, True)
add(DS, "time_slot", "Appointment time slot", "string", "HH:MM-HH:MM", False, True)
add(DS, "patient_count", "Number of patients in this slot", "int", "1-15", False, True)
add(DS, "status", "Slot status", "string", "Scheduled/Completed/Cancelled/Walk-in/Delayed", False, True)

DS = "or_bookings"
add(DS, "booking_id", "Unique OR booking identifier", "string", "OR-XXXX", False, True)
add(DS, "room", "Operating room name", "string", "OR-1 to OR-5", False, True)
add(DS, "doctor", "Lead surgeon name", "string", "free text", False, True)
add(DS, "department", "Surgical department", "string", "Surgery/ER/ICU", False, True)
add(DS, "booking_date", "Booking date - alias of date column", "string", "ISO date", False, False)
add(DS, "date", "Procedure date (YYYY-MM-DD)", "string", "ISO date", False, True)
add(DS, "time_slot", "Procedure time slot", "string", "HH:MM-HH:MM", False, True)
add(DS, "procedure", "Procedure name", "string", "free text", False, True)
add(DS, "procedure_type", "Procedure category", "string", "Elective/Emergency/Urgent", False, True)
add(DS, "procedure_duration_minutes", "Expected duration in minutes", "int", "30-240", False, False)
add(DS, "post_op_bed_required", "Whether a post-op bed is needed", "bool", "True/False", False, False)
add(DS, "status", "Booking status", "string", "Scheduled/Completed/Cancelled/In Progress", False, True)
add(DS, "notes", "Free-text notes", "string", "free text", False, False)

DS = "patient_tracking"
add(DS, "patient_id", "Unique patient identifier (anonymized)", "string", "PAT-XXXX", False, True)
add(DS, "patient_name_or_anonymized_id", "Anonymized name label", "string", "Patient-XXXX", False, True)
add(DS, "national_id_or_card_id_optional", "National ID - always null for privacy", "float", "null only", False, False)
add(DS, "entry_datetime", "Datetime of hospital entry", "string", "ISO datetime", False, True)
add(DS, "entry_method", "How patient entered hospital", "string", "Walk-in/Ambulance/Referral/Transfer", False, True)
add(DS, "department", "Department patient was triaged to", "string", "ER/ICU/General Ward/Surgery/Radiology", False, True)
add(DS, "assigned_bed_id", "Bed assigned (null if waiting)", "string", "BED-XXXX or null", False, True)
add(DS, "admission_status", "Admission outcome", "string", "Admitted/Waiting/Discharged/Transferred", False, True)
add(DS, "length_of_stay_hours", "Hours spent in hospital", "int", "1-120", False, False)
add(DS, "discharge_datetime", "Datetime of discharge (null if still admitted)", "string", "ISO datetime or null", False, True)
add(DS, "payment_status", "Payment state", "string", "Paid/Pending/Insurance/Exempt", False, False)
add(DS, "current_status", "Current patient status", "string", "Active/Discharged/Transferred", False, True)
add(DS, "notes", "Free-text clinical notes", "string", "free text", False, False)

DS = "department_status"
add(DS, "department", "Department name", "string", "ER/ICU/General Ward/Surgery/Radiology", False, True)
add(DS, "current_patients", "Patients present now", "int", ">=0", False, True)
add(DS, "occupied_beds", "Beds currently occupied", "int", ">=0", False, True)
add(DS, "available_beds", "Beds currently free", "int", ">=0", False, True)
add(DS, "total_beds", "Licensed bed count", "int", "20-130", False, True)
add(DS, "occupancy_rate", "Fraction occupied (occupied/total)", "float", "0.0-1.0", False, True)
add(DS, "needed_beds", "Model-recommended beds", "int", ">=0", False, True)
add(DS, "bed_shortage", "Beds below needed (0 if surplus)", "int", ">=0", False, True)
add(DS, "available_doctors", "Doctors on duty in this department", "int", ">=0", False, True)
add(DS, "needed_doctors", "Doctors required per patient ratio", "int", ">=0", False, True)
add(DS, "doctor_shortage", "Doctors below needed (0 if surplus)", "int", ">=0", False, True)
add(DS, "available_nurses", "Nurses on duty in this department", "int", ">=0", False, True)
add(DS, "needed_nurses", "Nurses required per patient ratio", "int", ">=0", False, True)
add(DS, "nurse_shortage", "Nurses below needed (0 if surplus)", "int", ">=0", False, True)
add(DS, "department_status", "Status label", "string", "Normal/Under Pressure/Critical", False, True)
add(DS, "pressure_level", "Pressure tier", "string", "Low/Medium/High/Critical", False, True)

DS = "what_if_scenarios"
add(DS, "scenario_id", "Unique scenario ID", "string", "WI-001 to WI-042", False, True)
add(DS, "scenario_name", "Human-readable scenario name", "string", "free text", False, True)
add(DS, "scenario_category", "Category of scenario", "string", "Mass Casualty/Epidemic/Staffing/Seasonal/Weather/Operational", False, True)
add(DS, "department", "Primarily affected department", "string", "ER/ICU/General Ward/All Departments", False, True)
add(DS, "time_window", "Simulation time window", "string", "e.g. 6h/12h/24h/72h", False, True)
add(DS, "demand_multiplier", "Multiplier applied to demand", "float", "0.5-3.0", False, True)
add(DS, "arrival_increase_percent", "Percent increase in patient arrivals", "int", "0-150", False, True)
add(DS, "bed_capacity_change_percent", "Percent change in bed availability", "int", "-50 to +30", False, True)
add(DS, "doctor_availability_change_percent", "Percent change in doctor availability", "int", "-50 to +20", False, True)
add(DS, "nurse_availability_change_percent", "Percent change in nurse availability", "int", "-50 to +20", False, True)
add(DS, "or_booking_change_percent", "Percent change in OR bookings", "int", "-100 to +50", False, True)
add(DS, "appointment_change_percent", "Percent change in appointments", "int", "-100 to +50", False, True)
add(DS, "discharge_delay_hours", "Additional hours of discharge delay", "int", "0-12", False, True)
add(DS, "severity_level", "Scenario severity", "string", "Low/Medium/High/Critical", False, True)
add(DS, "probability_level", "Likelihood of this scenario occurring", "string", "Low/Medium/High", False, True)
add(DS, "operational_risk", "Overall operational risk rating", "string", "Low/Medium/High/Critical", False, True)
add(DS, "affected_resources", "Resources impacted by this scenario", "string", "free text", False, True)
add(DS, "expected_system_response", "Expected system behaviour under this scenario", "string", "free text", False, True)
add(DS, "recommended_action", "Suggested operational action", "string", "free text", False, True)
add(DS, "escalation_required", "Whether escalation to management is needed", "string", "Yes/No", False, True)
add(DS, "notes", "Free-text notes", "string", "free text", False, False)

DS = "users (login accounts)"
add(DS, "username", "Login username used for authentication", "string", "e.g. admin1/stf-0001", False, True)
add(DS, "password", "Plain-text password in CSV (bcrypt-hashed in DB)", "string", "123456 (demo)", False, False)
add(DS, "name", "Display name shown in dashboard", "string", "free text", False, True)
add(DS, "role", "Access role determining dashboard tab visibility", "string", "admin/doctor/nurse", False, True)
add(DS, "department", "Primary department for role-filtered views", "string", "ER/ICU/General Ward/Surgery/Radiology/Management", False, True)

os.makedirs("data/updated_exports", exist_ok=True)
dd = pd.DataFrame(rows)
dd.to_csv("data/updated_exports/data_dictionary.csv", index=False)
print(f"data_dictionary.csv: {len(dd)} entries, {dd['dataset'].nunique()} datasets")
for ds, cnt in dd["dataset"].value_counts().items():
    print(f"  {ds}: {cnt} columns")
